# Generated by Django 4.1.5 on 2023-01-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinema",
            name="img4",
            field=models.ImageField(default="dfg", upload_to="media"),
            preserve_default=False,
        ),
    ]
